//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microstar.Production.PCBTest.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microstar.Production.PCBTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AC Current result is out of the error range. 的本地化字符串。
        /// </summary>
        public static string ACCurrentOutOfRange {
            get {
                return ResourceManager.GetString("ACCurrentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active power result is out of the error range. 的本地化字符串。
        /// </summary>
        public static string ActivePowerOutOfRange {
            get {
                return ResourceManager.GetString("ActivePowerOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AC Voltage result is out of the error range. 的本地化字符串。
        /// </summary>
        public static string ACVolOutOfRange {
            get {
                return ResourceManager.GetString("ACVolOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Circuit breaker test 的本地化字符串。
        /// </summary>
        public static string BreakerTest {
            get {
                return ResourceManager.GetString("BreakerTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Erase SPI Flash 的本地化字符串。
        /// </summary>
        public static string Command_EraseSpiFlash {
            get {
                return ResourceManager.GetString("Command_EraseSpiFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Programming 的本地化字符串。
        /// </summary>
        public static string Command_ForceProgram {
            get {
                return ResourceManager.GetString("Command_ForceProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Measure AC Current 的本地化字符串。
        /// </summary>
        public static string Command_MeasureACCurrent {
            get {
                return ResourceManager.GetString("Command_MeasureACCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Measure Active Power Command 的本地化字符串。
        /// </summary>
        public static string Command_MeasureActivePower {
            get {
                return ResourceManager.GetString("Command_MeasureActivePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Measure AC Voltage 的本地化字符串。
        /// </summary>
        public static string Command_MeasureACVoltage {
            get {
                return ResourceManager.GetString("Command_MeasureACVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Measure DC Current 的本地化字符串。
        /// </summary>
        public static string Command_MeasureDCCurrent {
            get {
                return ResourceManager.GetString("Command_MeasureDCCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Measure DC Voltage 的本地化字符串。
        /// </summary>
        public static string Command_MeasureDCVoltage {
            get {
                return ResourceManager.GetString("Command_MeasureDCVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Measure Pulse 的本地化字符串。
        /// </summary>
        public static string Command_MeasurePulse {
            get {
                return ResourceManager.GetString("Command_MeasurePulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Meter Communication 的本地化字符串。
        /// </summary>
        public static string Command_MeterCommunication {
            get {
                return ResourceManager.GetString("Command_MeterCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read I2C 的本地化字符串。
        /// </summary>
        public static string Command_ReadI2C {
            get {
                return ResourceManager.GetString("Command_ReadI2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read SPI Flash 的本地化字符串。
        /// </summary>
        public static string Command_ReadSpiFlash {
            get {
                return ResourceManager.GetString("Command_ReadSpiFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relay control 的本地化字符串。
        /// </summary>
        public static string Command_RelayControl {
            get {
                return ResourceManager.GetString("Command_RelayControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Second signal calibration 的本地化字符串。
        /// </summary>
        public static string Command_SecondSignalCalibration {
            get {
                return ResourceManager.GetString("Command_SecondSignalCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write I2C 的本地化字符串。
        /// </summary>
        public static string Command_WriteI2C {
            get {
                return ResourceManager.GetString("Command_WriteI2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write SPI Flash 的本地化字符串。
        /// </summary>
        public static string Command_WriteSpiFlash {
            get {
                return ResourceManager.GetString("Command_WriteSpiFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        public static string Common_Information {
            get {
                return ResourceManager.GetString("Common_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Question 的本地化字符串。
        /// </summary>
        public static string Common_Question {
            get {
                return ResourceManager.GetString("Common_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Common_Warning {
            get {
                return ResourceManager.GetString("Common_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DC Current result is out of the error range. 的本地化字符串。
        /// </summary>
        public static string DCCurrentOutOfRange {
            get {
                return ResourceManager.GetString("DCCurrentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DC Voltage result is out of the error range. 的本地化字符串。
        /// </summary>
        public static string DCVolOutOfRange {
            get {
                return ResourceManager.GetString("DCVolOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not supported command. 的本地化字符串。
        /// </summary>
        public static string ERR001 {
            get {
                return ResourceManager.GetString("ERR001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command format error. 的本地化字符串。
        /// </summary>
        public static string ERR003 {
            get {
                return ResourceManager.GetString("ERR003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read only but received write command. 的本地化字符串。
        /// </summary>
        public static string ERR004 {
            get {
                return ResourceManager.GetString("ERR004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write only but received read command. 的本地化字符串。
        /// </summary>
        public static string ERR005 {
            get {
                return ResourceManager.GetString("ERR005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BCC Error. 的本地化字符串。
        /// </summary>
        public static string ERR600 {
            get {
                return ResourceManager.GetString("ERR600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FLASH address illegal. 的本地化字符串。
        /// </summary>
        public static string ERR601 {
            get {
                return ResourceManager.GetString("ERR601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read length illegal. 的本地化字符串。
        /// </summary>
        public static string ERR602 {
            get {
                return ResourceManager.GetString("ERR602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Erase sector failed. 的本地化字符串。
        /// </summary>
        public static string ERR603 {
            get {
                return ResourceManager.GetString("ERR603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read FLASH failed. 的本地化字符串。
        /// </summary>
        public static string ERR604 {
            get {
                return ResourceManager.GetString("ERR604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write FLASH failed. 的本地化字符串。
        /// </summary>
        public static string ERR605 {
            get {
                return ResourceManager.GetString("ERR605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write data illegal. 的本地化字符串。
        /// </summary>
        public static string ERR606 {
            get {
                return ResourceManager.GetString("ERR606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chip select code illegal. 的本地化字符串。
        /// </summary>
        public static string ERR607 {
            get {
                return ResourceManager.GetString("ERR607", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I2C address illegal. 的本地化字符串。
        /// </summary>
        public static string ERR608 {
            get {
                return ResourceManager.GetString("ERR608", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read I2C failed. 的本地化字符串。
        /// </summary>
        public static string ERR609 {
            get {
                return ResourceManager.GetString("ERR609", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write I2C failed. 的本地化字符串。
        /// </summary>
        public static string ERR610 {
            get {
                return ResourceManager.GetString("ERR610", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force program length illegal. 的本地化字符串。
        /// </summary>
        public static string ERR611 {
            get {
                return ResourceManager.GetString("ERR611", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Voltage pin number error,should be in &apos;1&apos;-&apos;5&apos;. 的本地化字符串。
        /// </summary>
        public static string ERR612 {
            get {
                return ResourceManager.GetString("ERR612", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current pin number error,should be in &apos;1&apos;-&apos;2&apos;. 的本地化字符串。
        /// </summary>
        public static string ERR613 {
            get {
                return ResourceManager.GetString("ERR613", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range error,should be:&apos;L&apos;,&apos;M&apos; or &apos;S&apos;. 的本地化字符串。
        /// </summary>
        public static string ERR614 {
            get {
                return ResourceManager.GetString("ERR614", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phase error,should be:&apos;A&apos;,&apos;B&apos; or &apos;C&apos;. 的本地化字符串。
        /// </summary>
        public static string ERR615 {
            get {
                return ResourceManager.GetString("ERR615", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Com port error,should be: &apos;485_1&apos;， &apos;485_2&apos;，&apos;232&apos;，&apos;GK&apos;，&apos;HW&apos; or &apos;PLC&apos;. 的本地化字符串。
        /// </summary>
        public static string ERR616 {
            get {
                return ResourceManager.GetString("ERR616", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Baud rate error,should be:&apos;300&apos;, &apos;600&apos;, &apos;1200&apos;, &apos;2400&apos;, &apos;4800&apos;, &apos;9600&apos;, &apos;19200&apos; or &apos;38400&apos;. 的本地化字符串。
        /// </summary>
        public static string ERR617 {
            get {
                return ResourceManager.GetString("ERR617", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data bit error, should be: &apos;7&apos;or &apos;8&apos;. 的本地化字符串。
        /// </summary>
        public static string ERR618 {
            get {
                return ResourceManager.GetString("ERR618", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parity bit error，should be:&apos;N&apos;,&apos;E&apos; or &apos;O&apos;. 的本地化字符串。
        /// </summary>
        public static string ERR619 {
            get {
                return ResourceManager.GetString("ERR619", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open transparent channel failed. 的本地化字符串。
        /// </summary>
        public static string ERR620 {
            get {
                return ResourceManager.GetString("ERR620", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relay number error,should be &apos;0&apos; - &apos;21&apos;. 的本地化字符串。
        /// </summary>
        public static string ERR621 {
            get {
                return ResourceManager.GetString("ERR621", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relay action error,should be &apos;open&apos; or &apos;close&apos;. 的本地化字符串。
        /// </summary>
        public static string ERR622 {
            get {
                return ResourceManager.GetString("ERR622", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap folder_document {
            get {
                object obj = ResourceManager.GetObject("folder_document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 SPI chip number should be between 1-5. 的本地化字符串。
        /// </summary>
        public static string ForceProgramCommand_ChipNumberIllegal {
            get {
                return ResourceManager.GetString("ForceProgramCommand_ChipNumberIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} failed (1). Expected: {2}, Actual: {3}. 的本地化字符串。
        /// </summary>
        public static string ForceProgramCommand_ForceProgramErrorMessageFormat {
            get {
                return ResourceManager.GetString("ForceProgramCommand_ForceProgramErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 kBytes should be 32 or 64. 的本地化字符串。
        /// </summary>
        public static string ForceProgramCommand_LengthIllegal {
            get {
                return ResourceManager.GetString("ForceProgramCommand_LengthIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to set parameter for {0} command: {1} Parameter: {2}. 的本地化字符串。
        /// </summary>
        public static string ForceProgramCommand_WriteFailedMessageFormat {
            get {
                return ResourceManager.GetString("ForceProgramCommand_WriteFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User has canceled transmission 的本地化字符串。
        /// </summary>
        public static string ForceProgramDialog_CancelTransmit {
            get {
                return ResourceManager.GetString("ForceProgramDialog_CancelTransmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string ForceProgramDialog_CRC32Failed {
            get {
                return ResourceManager.GetString("ForceProgramDialog_CRC32Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string ForceProgramDialog_CRC32Success {
            get {
                return ResourceManager.GetString("ForceProgramDialog_CRC32Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The total frames count: {0}, now: {1} 的本地化字符串。
        /// </summary>
        public static string ForceProgramDialog_FramesCountFormat {
            get {
                return ResourceManager.GetString("ForceProgramDialog_FramesCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read from SPI Flash successfully 的本地化字符串。
        /// </summary>
        public static string ForceProgramDialog_ReadSpiCompleted {
            get {
                return ResourceManager.GetString("ForceProgramDialog_ReadSpiCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write to SPI Flash successfully 的本地化字符串。
        /// </summary>
        public static string ForceProgramDialog_WriteSpiCompleted {
            get {
                return ResourceManager.GetString("ForceProgramDialog_WriteSpiCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illegal response data frame. 的本地化字符串。
        /// </summary>
        public static string IllegalData {
            get {
                return ResourceManager.GetString("IllegalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Response data frame is incomplete. 的本地化字符串。
        /// </summary>
        public static string IncompleteData {
            get {
                return ResourceManager.GetString("IncompleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abnormal response data frame header or end of frame is incorrect. 的本地化字符串。
        /// </summary>
        public static string IncorrectHeadOrTail {
            get {
                return ResourceManager.GetString("IncorrectHeadOrTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Response packet is incorrect. 的本地化字符串。
        /// </summary>
        public static string IncorrectResponse {
            get {
                return ResourceManager.GetString("IncorrectResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12V voltage 的本地化字符串。
        /// </summary>
        public static string Item_12Vvoltage {
            get {
                return ResourceManager.GetString("Item_12Vvoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 232 communication (1) 的本地化字符串。
        /// </summary>
        public static string Item_232Communication1 {
            get {
                return ResourceManager.GetString("Item_232Communication1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 232 communication (2) 的本地化字符串。
        /// </summary>
        public static string Item_232Communication2 {
            get {
                return ResourceManager.GetString("Item_232Communication2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 485 communication (1) 的本地化字符串。
        /// </summary>
        public static string Item_485Communication1 {
            get {
                return ResourceManager.GetString("Item_485Communication1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 485 communication (2) 的本地化字符串。
        /// </summary>
        public static string Item_485Communication2 {
            get {
                return ResourceManager.GetString("Item_485Communication2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 485 communication (3) 的本地化字符串。
        /// </summary>
        public static string Item_485Communication3 {
            get {
                return ResourceManager.GetString("Item_485Communication3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 485 voltage 的本地化字符串。
        /// </summary>
        public static string Item_485Voltage {
            get {
                return ResourceManager.GetString("Item_485Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5V voltage 的本地化字符串。
        /// </summary>
        public static string Item_5Vvoltage {
            get {
                return ResourceManager.GetString("Item_5Vvoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auxiliary power supply 12V voltage 的本地化字符串。
        /// </summary>
        public static string Item_AuxiliaryPowerSupply12Vvoltage {
            get {
                return ResourceManager.GetString("Item_AuxiliaryPowerSupply12Vvoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auxiliary power supply 485 voltage 的本地化字符串。
        /// </summary>
        public static string Item_AuxiliaryPowerSupply485voltage {
            get {
                return ResourceManager.GetString("Item_AuxiliaryPowerSupply485voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auxiliary power supply 5V voltage 的本地化字符串。
        /// </summary>
        public static string Item_AuxiliaryPowerSupply5Vvoltage {
            get {
                return ResourceManager.GetString("Item_AuxiliaryPowerSupply5Vvoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backlight voltage 的本地化字符串。
        /// </summary>
        public static string Item_BacklightVoltage {
            get {
                return ResourceManager.GetString("Item_BacklightVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery current (1) 的本地化字符串。
        /// </summary>
        public static string Item_BatteryCurrent1 {
            get {
                return ResourceManager.GetString("Item_BatteryCurrent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery current (2) 的本地化字符串。
        /// </summary>
        public static string Item_BatteryCurrent2 {
            get {
                return ResourceManager.GetString("Item_BatteryCurrent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Circuit breaker control (1) 的本地化字符串。
        /// </summary>
        public static string Item_CircuitBreakerControl1 {
            get {
                return ResourceManager.GetString("Item_CircuitBreakerControl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Circuit breaker control (2) 的本地化字符串。
        /// </summary>
        public static string Item_CircuitBreakerControl2 {
            get {
                return ResourceManager.GetString("Item_CircuitBreakerControl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External magnetic field test (1) 的本地化字符串。
        /// </summary>
        public static string Item_ExternalMagneticFieldTest1 {
            get {
                return ResourceManager.GetString("Item_ExternalMagneticFieldTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External magnetic field test (2) 的本地化字符串。
        /// </summary>
        public static string Item_ExternalMagneticFieldTest2 {
            get {
                return ResourceManager.GetString("Item_ExternalMagneticFieldTest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force programming 的本地化字符串。
        /// </summary>
        public static string Item_ForceProgramming {
            get {
                return ResourceManager.GetString("Item_ForceProgramming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Infrared communication 的本地化字符串。
        /// </summary>
        public static string Item_InfraredCommunication {
            get {
                return ResourceManager.GetString("Item_InfraredCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optical port communication 的本地化字符串。
        /// </summary>
        public static string Item_OpticalCommunication {
            get {
                return ResourceManager.GetString("Item_OpticalCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phase A power consumption 的本地化字符串。
        /// </summary>
        public static string Item_PhaseAPowerConsumption {
            get {
                return ResourceManager.GetString("Item_PhaseAPowerConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phase B power consumption 的本地化字符串。
        /// </summary>
        public static string Item_PhaseBPowerConsumption {
            get {
                return ResourceManager.GetString("Item_PhaseBPowerConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phase C power consumption 的本地化字符串。
        /// </summary>
        public static string Item_PhaseCPowerConsumption {
            get {
                return ResourceManager.GetString("Item_PhaseCPowerConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pulse test 的本地化字符串。
        /// </summary>
        public static string Item_PulseTest {
            get {
                return ResourceManager.GetString("Item_PulseTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relay control (1) 的本地化字符串。
        /// </summary>
        public static string Item_RelayControl1 {
            get {
                return ResourceManager.GetString("Item_RelayControl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relay control (2) 的本地化字符串。
        /// </summary>
        public static string Item_RelayControl2 {
            get {
                return ResourceManager.GetString("Item_RelayControl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RJ45 port voltage (1) 的本地化字符串。
        /// </summary>
        public static string Item_RJ45PortVoltage1 {
            get {
                return ResourceManager.GetString("Item_RJ45PortVoltage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RJ45 port voltage (2) 的本地化字符串。
        /// </summary>
        public static string Item_RJ45PortVoltage2 {
            get {
                return ResourceManager.GetString("Item_RJ45PortVoltage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Second signal test 的本地化字符串。
        /// </summary>
        public static string Item_SecondSignalTest {
            get {
                return ResourceManager.GetString("Item_SecondSignalTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop reading current 的本地化字符串。
        /// </summary>
        public static string Item_StopReadingCurrent {
            get {
                return ResourceManager.GetString("Item_StopReadingCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap landing {
            get {
                object obj = ResourceManager.GetObject("landing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Meter circuit board test items 的本地化字符串。
        /// </summary>
        public static string Landing_MeterTestItems {
            get {
                return ResourceManager.GetString("Landing_MeterTestItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switching power board test items 的本地化字符串。
        /// </summary>
        public static string Landing_PowerTestItems {
            get {
                return ResourceManager.GetString("Landing_PowerTestItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The username or password is incorrect. 的本地化字符串。
        /// </summary>
        public static string LoginDialog_LoginFailed {
            get {
                return ResourceManager.GetString("LoginDialog_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password can&apos;t be empty. 的本地化字符串。
        /// </summary>
        public static string LoginDialog_PasswordEmpty {
            get {
                return ResourceManager.GetString("LoginDialog_PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username can&apos;t be empty. 的本地化字符串。
        /// </summary>
        public static string LoginDialog_UserNameEmpty {
            get {
                return ResourceManager.GetString("LoginDialog_UserNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input meter number. 的本地化字符串。
        /// </summary>
        public static string MainForm_InputMeterNumber {
            get {
                return ResourceManager.GetString("MainForm_InputMeterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t find the user. 的本地化字符串。
        /// </summary>
        public static string MainForm_NoUser {
            get {
                return ResourceManager.GetString("MainForm_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string MainForm_StartTest {
            get {
                return ResourceManager.GetString("MainForm_StartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string MainForm_StopTest {
            get {
                return ResourceManager.GetString("MainForm_StopTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} failed (PinNumber = {1}, CurrentRange = {2}, Phase = {3}). Expected: {4}, Actual: {5}. 的本地化字符串。
        /// </summary>
        public static string MeasureCommandBase_MeasureErrorMessageFormat {
            get {
                return ResourceManager.GetString("MeasureCommandBase_MeasureErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to parse measurement value. Expected: decimal + unit; Actual: {0} 的本地化字符串。
        /// </summary>
        public static string MeasureCommandBase_ParseFailedMessageFormat {
            get {
                return ResourceManager.GetString("MeasureCommandBase_ParseFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read measure result for {0} command: {1} Parameter: {2}. 的本地化字符串。
        /// </summary>
        public static string MeasureCommandBase_ReadResultFailedMessageFormat {
            get {
                return ResourceManager.GetString("MeasureCommandBase_ReadResultFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to start measuring for {0} command: {1} Parameter: {2}. 的本地化字符串。
        /// </summary>
        public static string MeasureCommandBase_StartFailedMessageFormat {
            get {
                return ResourceManager.GetString("MeasureCommandBase_StartFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} failed ({1}). Expected: {2}, Actual: {3}. 的本地化字符串。
        /// </summary>
        public static string MeterCommunicationCommand_CommErrorMessageFormat {
            get {
                return ResourceManager.GetString("MeterCommunicationCommand_CommErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to communicate with meter for {0} command: {1}. Parameter: {2}. 的本地化字符串。
        /// </summary>
        public static string MeterCommunicationCommand_WriteFailedMessageFormat {
            get {
                return ResourceManager.GetString("MeterCommunicationCommand_WriteFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap NOOK {
            get {
                object obj = ResourceManager.GetObject("NOOK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Port name or baudrate cannot be null. 的本地化字符串。
        /// </summary>
        public static string NullArguments {
            get {
                return ResourceManager.GetString("NullArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap OK {
            get {
                object obj = ResourceManager.GetObject("OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ok_900200 {
            get {
                object obj = ResourceManager.GetObject("ok_900200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Already the last page. 的本地化字符串。
        /// </summary>
        public static string PagerControl_LastPage {
            get {
                return ResourceManager.GetString("PagerControl_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please fill in the correct page number. 的本地化字符串。
        /// </summary>
        public static string PagerControl_WrongPage {
            get {
                return ResourceManager.GetString("PagerControl_WrongPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The circuit board does not reply the frame to PC. Please check the hardware connection or check board status. 的本地化字符串。
        /// </summary>
        public static string PcbTesterClient_NoBoard {
            get {
                return ResourceManager.GetString("PcbTesterClient_NoBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profile for this test item was not found. 的本地化字符串。
        /// </summary>
        public static string ProfileManager_NoProfile {
            get {
                return ResourceManager.GetString("ProfileManager_NoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} failed (Address = 0x{1:X8}, Length = {2}). Expected: {3}, Actual: {4}. 的本地化字符串。
        /// </summary>
        public static string ReadAddressCommandBase_ReadErrorMessageFormat {
            get {
                return ResourceManager.GetString("ReadAddressCommandBase_ReadErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read address for {0} command: {1}. Parameter: {2}. 的本地化字符串。
        /// </summary>
        public static string ReadAddressCommandBase_ReadFailedMessageFormat {
            get {
                return ResourceManager.GetString("ReadAddressCommandBase_ReadFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to set relay control parameter for {0} command: {1} Parameter: {2}. 的本地化字符串。
        /// </summary>
        public static string RelayControlCommand_WriteFailedMessageFormat {
            get {
                return ResourceManager.GetString("RelayControlCommand_WriteFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unqualified 的本地化字符串。
        /// </summary>
        public static string Result_Failed {
            get {
                return ResourceManager.GetString("Result_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Qualified 的本地化字符串。
        /// </summary>
        public static string Result_Success {
            get {
                return ResourceManager.GetString("Result_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} failed ({1}). Expected: {2}, Actual: {3}. 的本地化字符串。
        /// </summary>
        public static string SecondSignalCalibrationCommand_MeasureErrorMessageFormat {
            get {
                return ResourceManager.GetString("SecondSignalCalibrationCommand_MeasureErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no clock signal value. 的本地化字符串。
        /// </summary>
        public static string SecondSignalCalibrationCommand_NoValue {
            get {
                return ResourceManager.GetString("SecondSignalCalibrationCommand_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read second result for {0} command: {1} Parameter: {2}. 的本地化字符串。
        /// </summary>
        public static string SecondSignalCalibrationCommand_ReadResultFailedMessageFormat {
            get {
                return ResourceManager.GetString("SecondSignalCalibrationCommand_ReadResultFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to start testing second for {0} command: {1} Parameter: {2}. 的本地化字符串。
        /// </summary>
        public static string SecondSignalCalibrationCommand_WriteFailedMessageFormat {
            get {
                return ResourceManager.GetString("SecondSignalCalibrationCommand_WriteFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The serial port is not open. 的本地化字符串。
        /// </summary>
        public static string SerialPortNoOpen {
            get {
                return ResourceManager.GetString("SerialPortNoOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Serial port can be used. 的本地化字符串。
        /// </summary>
        public static string SerialSettingsDialog_NoUsedPort {
            get {
                return ResourceManager.GetString("SerialSettingsDialog_NoUsedPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse 的本地化字符串。
        /// </summary>
        public static string TestInterface_CollapseRecord {
            get {
                return ResourceManager.GetString("TestInterface_CollapseRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand 的本地化字符串。
        /// </summary>
        public static string TestInterface_ExpandRecord {
            get {
                return ResourceManager.GetString("TestInterface_ExpandRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive data timeout. 的本地化字符串。
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this user? 的本地化字符串。
        /// </summary>
        public static string UserManageDialog_DeleteUser {
            get {
                return ResourceManager.GetString("UserManageDialog_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to write address for {0} command: {1} Parameter: {2}. 的本地化字符串。
        /// </summary>
        public static string WriteAddressCommandBase_WriteFailedMessageFormat {
            get {
                return ResourceManager.GetString("WriteAddressCommandBase_WriteFailedMessageFormat", resourceCulture);
            }
        }
    }
}
